Save the destroy script

diff --git a/openstack-server b/openstack-server
--- a/openstack-server
+++ b/openstack-server
@@ -66,6 +66,11 @@ readonly \
 	server_image  \
 	key_name      \
 	external_network
+declare -r destroy_file="${XDG_CACHE_HOME:-${HOME}/.cache}/openstack-server/${OS_CLOUD}-${name}-destroy.sh"
+if [[ -f "$destroy_file" ]]; then
+	>&2 echo "Destroy file found. Please be more creative with your server name. Aborting..."
+	exit 1
+fi
 
 declare \
 	sg_id=''      \
@@ -108,8 +113,8 @@ cleanup() {
 trap cleanup EXIT
 
 print_cleanup_script() {
-	cat <<EOF
-# Below the instructions to undo.
+	cat > "$destroy_file" <<EOF
+# Below the instructions to destroy the server "${name}" on the cloud "${OS_CLOUD}".
 openstack floating ip delete "$fip_id" || >&2 echo "Failed to delete FIP $fip_id"
 openstack server delete "$server_id" || >&2 echo "Failed to delete server $server_id"
 openstack port delete "$port_id" || >&2 echo "Failed to delete port $port_id"
@@ -119,7 +124,6 @@ openstack subnet delete "$subnet_id" || >&2 echo "Failed to delete subnet $subne
 openstack network delete "$network_id" || >&2 echo "Failed to delete network $network_id"
 openstack security group delete "$sg_id" || >&2 echo "Failed to delete security group $sg_id"
 EOF
-
 }
 
 sg_id="$(openstack security group create -f value -c id "$name")"
